name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: stsfaroz/metrics@master
        with:
          filename: iso_calender.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - uses: stsfaroz/metrics@master
        with:
          template: terminal
          filename: contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: Asia/Kolkata
          plugin_notable: yes
          plugin_notable_from: all
      - uses: stsfaroz/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
          config_timezone: Asia/Kolkata
